# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Minhinified
subtitle: decoding the dev life
email: hlminh2000@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a Toronto-based software developer. I love code, music, working out,...
  but above all I love being active in the tech scene as a student and 
  a mentor. 
  
  This website records everything I do in the community and all the things
  I've learned for the purpose of decoding what it is like to be a developer.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://minhified.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hlminh2000
github_username:  hlminh2000
github_url:       https://github.com/hlminh2000
linkedin_url:     https://www.linkedin.com/in/le-minh-ha-57644440
medium_username:  haleminh
medium_url:       https://medium.com/@haleminh

# Visual settings
tiles-count: 3
tiles-source: posts

# Build settings
markdown: kramdown
theme: forty_jekyll_theme
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
